name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Setup Node
      uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
